### ISSUE TITLE
Undetected aliasing in constructor application

### ISSUE THREAD

**Issue by yannbolliger** [epfl-lara/stainless#1075]
The following example fails, because the aliasing that happens when `Mut(a)` is created is not recognised.

```scala
import stainless.annotation._

object Test {
  final case class Mut[@mutable T](var t: T)
  final case class S(var s: Int)

  def f2() = {
    val a = S(1)
    val b = Mut(a)
    b.t.s = 100
    assert(a.s == 100)
  }
}
```

<details>
<summary>Resulting trees</summary>

After AntiAliasing
```scala
def f2: Unit = {
  var a: S = S(1)
  var b: Mut[S] = Mut[S](a)
  b = Mut[S](S(100))
  ()
  assert(a.s == 100)
  ()
}
```

After ImperativeCodeElimination
```scala
def f2: Unit = {
  val a: S = S(1)
  val b: Mut[S] = Mut[S](a)
  val b: Mut[S] = Mut[S](S(100))
  val tmp: Unit = ()
  val tmp: Unit = ()
  assert(a.s == 100)
  ()
}
```

</details>

**Comment by jad-hamza** [comment]
Maybe that property isn't enough after all?
https://github.com/epfl-lara/stainless/blob/8fa04b5b931d788896585e51e836cf2a715884a4/core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala#L347-L348

Here the targets of `b` are empty and then we enter the rest of the code with the rewriting `b -> b` (is that normal?).

**Comment by samarion** [comment]
This check seems too weak: https://github.com/epfl-lara/stainless/blob/8fa04b5b931d788896585e51e836cf2a715884a4/core/src/main/scala/stainless/extraction/imperative/EffectsChecker.scala#L80-L81

I think for this check, we would need `getTargets` to throw an exception in the `ADT` (and other) cases like it did before. Maybe we can change `getTargets` to have a "precise" mode where it throws an exception instead of returning an empty set when it can't compute targets.

**Comment by samarion** [comment]
Yes, it should be rejected, but not exactly because of the `Mut(a)` construction. @jad-hamza added some support for aliasing when the aliased variable is never used afterwards. So if we didn't have the `assert(a.s == 100)` statement in the program, it should be transformed correctly.

**Comment by samarion** [comment]
Supporting this kind of aliasing more generally would require a significant change in the existing aliasing analysis, and it's not clear how significant the improvement would be. I think it would make more sense to invest in @gsps' new aliasing transformation instead since it isn't limited by the analysis.

**Comment by jad-hamza** [comment]
Is it normal that we enter the rest of the code with the rewriting `b -> b`, as opposed to `b -> Mut(a)`?

Also, what are the property of the strict and non-strict `getTargets`? Currently, I wrote:
```scala
  // getTargets(expr, Seq()) returns the set of targets such that after `var x = expr`,
  // the modifications on `x` will result in modifications on these targets
```
For the non-strict one, maybe it should be `the direct modifications (field assignments, array updates, etc.) on x will result [...]`, and for the strict one, it should be `the modifications (after possibly many field accesses) on x will return [...]`?

And here we'd use the strict version:
https://github.com/epfl-lara/stainless/blob/8fa04b5b931d788896585e51e836cf2a715884a4/core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala#L343
While here we'd use the non-strict version:
https://github.com/epfl-lara/stainless/blob/8fa04b5b931d788896585e51e836cf2a715884a4/core/src/main/scala/stainless/extraction/imperative/AntiAliasing.scala#L426

Is this what you have in mind?

**Comment by samarion** [comment]
> Is it normal that we enter the rest of the code with the rewriting b -> b, as opposed to b -> Mut(a)?

No, it's not normal, but it happens because `getTargets` (incorrectly) returned an empty set for `Mut(a)` when it should have thrown an exception instead.

> Also, what are the property of the strict and non-strict getTargets?

Your explanation seems pretty good. I would maybe qualify the second case as "the **arbitrary** modifications", but up to you.

> And here we'd use the strict version:

Yep, that looks correct.

**Comment by yannbolliger** [comment]
Should I fix that, or can I leave that to anyone of you?

**Comment by jad-hamza** [comment]
Sure you can! Otherwise I'll do it next week.
