### ISSUE TITLE
sbt integration

### ISSUE THREAD

**Issue by vkuncak** [epfl-lara/stainless#155]
[Iulian and Mirco]

Enable compilation of projects consisting of ordinary .scala files that are compiled as usual, as well as files with .v.scala double extension that are verified with stainless using the included stainless dependencies and then compiled as usual.

**Comment by dragos** [comment]
We'll try this first instead of the specific source directory (`src/stainless/scala` -- *configuration* in Sbt parlance). The advantage of this config is that Sbt can handle dependencies independently from other configurations, so we can stuff additional jars without leaking into "main" sources. However, I agree that `.v.stainless` is very nice too.

**Comment by Phenitei** [comment]
There is an sbt plugin developed here: https://github.com/NiceKingWei/sbt-stainless ; it adds a task `verify` which calls on stainless as if one had called it from the command line. Maybe coordinate with @NiceKingWei ?
