### ISSUE TITLE
Missing some nodes in Registry

### ISSUE THREAD

**Issue by ak807** [epfl-lara/stainless#165]
Hi All, 

I have just started experimenting with Stainless and was wondering if you could help me with an
error message that I am getting. The message is not very informative so I am not sure how to diagnose it.

I am using the following Stainless version:
commit: b9b28d55b5c4f057049e6eafd51e9b765688e8a6

Please let me know if you need more information (e.g., scalac version etc.).

So, I am running the `stainless-scalac` without any other options for the following program:

    package example

    class myInt(val value:Int) {}

    class Test {
        def get_value(x:myInt) : Int = {
        x.value
        }
    }

The exact output I am getting is the following:

    [Warning ] Parallelism is disabled.
    [ Error  ] get_value$0 depends on missing dependencies: value$0.
    [Internal] Missing some nodes in Registry: value$0
    [Internal] Please inform the authors of Inox about this message

What does this error message mean ?
Note that I am not using any verification conditions yet.

Thanks in advance !

**Comment by Phenitei** [comment]
Hi,

I believe this is because you have defined `myInt` as a `class` and not a `case class`; therefore accessing the `value` variable like this is not supported in stainless: creation of ADTs is only supported through `case class`es. See the documentation on Pure Scala for more information!

You can rewrite your example as:
```scala
package example

case class MyInt(value: Int)

class Test {
  def get_value(x: MyInt): Int = {
    x.value
  }
}
```
Though that example becomes a bit nonsensical since scala creates getters for you in case classes.

Hope this helps!

**Comment by ak807** [comment]
Thanks Phenitei that was very helpful !
I am actually new to Scala so I am curious ... is there a reason why non-case classes are not supported by stainless ?

I agree it is a nonsensical example :). I was actually trying to do something else and this was the minimal failing test I could come up with to demonstrate the issue.

P.S.: If I could offer some feedback as a new user of Stainless I would suggest error messages of the form "feature <x> not supported by stainless" as a way of reporting such errors.

Thanks again !

**Comment by vkuncak** [comment]
Case classes have a much simpler mathematical model than non-case classes. They map to algebraic data types where equality is structural. For example, if x::xs == y::ys, then x==y and xs==ys. For general classes, only the opposite direction of this implication holds. Depending on the notion of equality you would have for other classes, you would get different algebraic theories for values of those classes. Those may not be supported directly by the SMT solvers, so one may need to do some encoding. Note that implementing "new" and reference equality requires reasoning about state, since you have that "new Foo == new Foo" evaluates to false.

**Comment by ak807** [comment]
Thanks for the helpful responses/explanations !
