### ISSUE TITLE
Inconsistent counter examples

### ISSUE THREAD

**Issue by ak807** [epfl-lara/stainless#170]
Hi All,

I am trying to reproduce the TestMax example from the tutorial which is the following:

```scala
class TestMax {
  def max(x: Int, y: Int): Int = {
    val d = x - y
    if (d > 0) {
        x
    } else { 
        y
    }
} ensuring(res => x <= res && y <= res && (res == x || res == y))
```

I am using stainless commit: `a114d6c73b43242dfdfe31476c408993653dd8e3` from master branch and command: `stainless-scalac` without any options.

From the above example, the counter example I am getting is this:

```
[Warning ] Found counter-example:
[Warning ]   x: Int -> -1577058301
[Warning ]   y: Int -> 1644167171
```

So far so good. However, if I try to wrap the integer type around a case class like this:

```scala
case class Int128(v : Int) {
    def - (that : Int128) = new Int128(this.v - that.v)
    def > (that : Int128) = this.v > that.v
    def > (that : Int) = this.v > that
    def <= (that : Int128) = this.v <= that.v
}

class TestMax {
    def max(x: Int128, y: Int128): Int128 = {
        val d = x - y
        if (d > 0) {
            x
        } else { 
            y
        }
    } ensuring(res => x <= res && y <= res && (res == x || res == y))
}
```

I am getting a different counter-example:

```
[Warning ] Found counter-example:
[Warning ]   y: Int128 -> Int128(2114728512)
[Warning ]   x: Int128 -> Int128(-2146991335)
```

Is this behavior expected ?

Thanks !

**Comment by jad-hamza** [comment]
> Is this behavior expected ?

Yes I think it's normal to obtain different counter-examples for similar programs, because these are generated by the underlying SMT solvers (Z3, CVC4) and when there are many counter-examples to a property, there is no guarantee that the solvers always return the same counter-examples (for similar programs). 

You can also check whether a counter-example is indeed a counter-example using --check-models, which should always be the case in principle (except for bugs or edge cases)

**Comment by ak807** [comment]
Thanks !
