### ISSUE TITLE
Typing error with partial if statements

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#24]
This works fine when f has type BigInt => BigInt, but doesn't work as is:

> <untyped>@?:? (of class inox.ast.Types$Untyped$) is unsupported by solver z3

```scala
object Untyped {

  def untyped(f: Wrap[BigInt,BigInt])  {
    if (f(0) < 0) {
      f(0)
    } 

    f(0)
  } 
}

case class Wrap[A,B](f: A => B) {
  def apply(k: A): B = {
    f(k)
  }
}
```

**Comment by samarion** [comment]
This is actually quite tricky... We usually rely on the Scala compiler to inject the required `Unit` literals when necessary, but here the condition gets extracted as
```scala
if (apply(f, 0) < 0) {
  apply(f, 0)
} else {
  ()
}
```
which has type `Any`.

A naive fix would be to simply inject a unit literal after the call to `apply(f, 0)` in the then branch, however if the expression were instead
```scala
val a: Any = if (apply(f, 0) < 0) {
  apply(f, 0)
} else {
  ()
}
```
then the semantics wouldn't be preserved since `a` would be a unit constant instead of taking the value `apply(f, 0)` in certain cases...

I'll need to think about this a little more and how it interacts with the new support for subtyping...

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/stainless/commit/26b3ff77d6dc70431b75d704612fd3232c1aa98f
