### ISSUE TITLE
Crash when using & instead of && for Booleans

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#31]
The `&` operator produces a crash with an exception

> Exception in thread "main" inox.ast.TypeOps$TypeErrorException: Type error

```scala
object Untyped {
  def untyped(a: Boolean) = {
    require(a & a)    
    assert(true)
  }
}
```

**Comment by mantognini** [comment]
Currently Inox doesn't support `& | ^` on `Boolean`, but [it should](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.22.2). I'll add support for that as well in epfl-lara/inox#26.

**Comment by samarion** [comment]
Hmm, I'm not sure we actually need these within Inox. The operators are easy to encode using let bindings, `&&` and `||`. In general, I'd prefer Inox to stay as simple as possible and handle such encoding / extraction issues within Stainless itself.

**Comment by mantognini** [comment]
The issue I see with mapping it to `&&` and `||` is that those don't have the same semantics (short-circuit doesn't apply on `&` and `|`). As for `^`, we could use `!=` but it wouldn't have the same operator precedence. Wouldn't that create more issues in the long term? (The way I planned to modify inox was limited to `BV*` operators.)

**Comment by samarion** [comment]
If you use
```scala
val a = b1
val b = b2
a && b
```
you get the same semantics as `&` (and similar encodings for the other ones).

About operator precedence, I don't mean we should not support these operators in the frontend (namely Stainless), but I don't think they are required in the solving backend (namely Inox). Operator precedence isn't really an issue in Inox since we aren't going to be parsing anything.

If you meant that you would only be adding support for these within the Stainless PR linked to https://github.com/epfl-lara/inox/pull/26, then I completely agree :)

**Comment by mantognini** [comment]
I now see your point. Patch will be available through stainless only.

**Comment by mantognini** [comment]
Support for this is included in #33.

**Comment by jad-hamza** [comment]
The original example is now emitting this exception:

> [Internal] java.util.NoSuchElementException: key not found: class stainless.extraction.imperative.Trees$BoolBitwiseAnd

**Comment by samarion** [comment]
Re-fixed in https://github.com/epfl-lara/stainless/commit/d322b4a6792cc30516b79948e70669219c9e14a8
