### ISSUE TITLE
Allow ghost effects on ghost fields of inductive ADTs

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#346]
The first example is accepted by the ghost checker, but not the second one:

```scala
import stainless.annotation._
import stainless.lang._
import stainless.collection._

object Ghost {
  case class Ghost(@ghost var p: BigInt) {
    def f(x: BigInt) = {
      ghost {
        p = p + 1
      }
    }
  }
}
```

```scala
import stainless.annotation._
import stainless.lang._
import stainless.collection._

object Ghost {
  case class Ghost(@ghost var l: List[BigInt]) {
    def f(x: BigInt) = {
      ghost {
        l = x :: l // Argument to ghost parameter `value` of `ghost` must only have effects on ghost fields
      }
    }
  }
}
```

**Comment by jad-hamza** [comment]
Another test that fails for the same reason (@samarion said effects analysis is not precise enough at the moment)

```scala
import stainless.annotation._
import stainless.collection._

object Ghost {
  case class Ghost(@ghost var l: List[BigInt]) {
    @ghost
    def add(x: BigInt) = {
      l = x :: l
    }
  }
}
```

**Comment by romac** [comment]
Yeah it looks like we lose information about the effect target (ie. the ghost field `l`) because of this [call](https://github.com/epfl-lara/stainless/blob/6e0a6f118ee00b5093616885924a0b79e452a953/core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala#L359) to [`truncate`](https://github.com/epfl-lara/stainless/blob/6e0a6f118ee00b5093616885924a0b79e452a953/core/src/main/scala/stainless/extraction/imperative/EffectsAnalyzer.scala#L320-L342). Commenting the call allows both examples through.

**Comment by romac** [comment]
In both the second and third example, `Ghost` is treated as an inductive ADT as it contains a `List`, and the effect target is thus truncated from `this.l` to just `this`.

**Comment by samarion** [comment]
Fixed in https://github.com/epfl-lara/stainless/commit/2a991ab9a9a1ebc3b5ed1511bd45c870ca237813
