### ISSUE TITLE
Updates of variables inside traits

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#358]
```scala
trait A {
  var x: BigInt

  def f() = {
    x = 0
    assert(x == 0)
  }
}
```

Output from Stainless

```
[  Info  ]  - Result for 'body assertion' VC for f @6:5:
[Warning ]  => INVALID
[Warning ] Found counter-example:
[Warning ]   thiss: A -> Open(0)
[Warning ]   
[Warning ]   x(thiss: A) -> if (thiss == Open(0)) {
[Warning ]     1
[Warning ]   } else {
[Warning ]     choose(((res: BigInt) @unchecked) => true)
[Warning ]   }
```

The trees (the call to `x_=` should return a new `A` after the imperative phases):

```scala
[ Debug  ] Symbols after FunctionInlining
[ Debug  ] 
[ Debug  ] -------------Functions-------------
[ Debug  ] def f(thiss: A): Unit = {
[ Debug  ]   val tmp: Unit = x_=(thiss, 0)
[ Debug  ]   assert(x(thiss) == 0)
[ Debug  ]   ()
[ Debug  ] }
```

**Comment by romac** [comment]
I don't think this is a bug, because I think (haven't tested, sorry) that you would get the same result when turning `A` into a sealed trait and extending it as follows:

```scala
case class B() extends A {
  def x = 42
  def x_=(y: BigInt) = ()
}
```

That's why you are getting a counter-example with `Open(0)`.

Keep in mind that abstract variables in trait are desugared by the Scala compiler as an abstract getter and an abstract setter, nothing else.

**Comment by jad-hamza** [comment]
Ah yes thanks! You're right. (This example isn't accepted but I see what you mean)

I think it would make sense to say that within Stainless, these setters and getters always have the "normal" behavior and cannot be overridden (that would deviate a bit from Scala).

But it's not a big deal, I'll try to find a workaround for the moment.

**Comment by samarion** [comment]
I agree with Jad about this, the usual Scala behavior basically makes these trait vars basically useless otherwise. The system should add a postcondition to accessors that ensure the getter is indeed equal to the input after the setter has been called. The difficulty consists in making sure that all other getters will still return the same value.

**Comment by romac** [comment]
> The difficulty consists in making sure that all other getters will still return the same value.

Can you expand on that, I am not sure I see what you mean here? Otherwise yeah, I agree as well.

**Comment by samarion** [comment]
If we use the same approach as for extern functions, all fields of the trait can potentially take on new values after going through a setter update. The postcondition stating that the getter associated to the field now has the input value won't constraint the other fields of the trait. This would make verifying useful properties about the trait basically impossible. So we need to find out exactly what other fields the trait contains and make sure their values stay the same.

**Comment by samarion** [comment]
Fixed by https://github.com/epfl-lara/stainless/pull/370
