### ISSUE TITLE
Long compilation/extraction time

### ISSUE THREAD

**Issue by OlivierBlanvillain** [epfl-lara/stainless#38]
I'm currently investigating stainless long compilation/extraction time. The file I'm working on is about 150 loc and takes more that 200 seconds to pass stainless' extraction (vs ~4 seconds to compile with scalac), which, due to the lack of incrementally, is currently a blocker issue that prevents me to work on the verification part of my task.

On my way through minimization, I've found something interesting that might help understand the issue. I've managed to split my file into 2 independently compiling files such that the compilation/extraction time do no compose as you would expect:

```scala
$ sbt
> stainless-scalac/run --functions=nope 1.scala
[info] Running stainless.Main --functions=nope 1.scala
[info] [  Info  ] No verification conditions were analyzed.
[success] Total time: 15 s, completed May 25, 2017 1:27:24 PM

> stainless-scalac/run --functions=nope 2.scala
[info] Running stainless.Main --functions=nope 2.scala
[info] [  Info  ] No verification conditions were analyzed.
[success] Total time: 125 s, completed May 25, 2017 1:29:39 PM

> stainless-scalac/run --functions=nope 1.scala 2.scala
[info] Running stainless.Main --functions=nope 1.scala 2.scala
[info] [  Info  ] No verification conditions were analyzed.
[success] Total time: 211 s, completed May 25, 2017 1:33:48 PM
```

I would expect the processing of both files at once to be faster than processing them individually, which is what happens with `scalac`:

```scala
$ time scalac 1.scala
real    0m2.686s
user    0m7.152s
sys     0m0.136s

$ time scalac 2.scala
real    0m3.287s
user    0m9.084s
sys     0m0.180s

$ time scalac 1.scala 2.scala
real    0m3.433s
user    0m9.616s
sys     0m0.236s
```

Any idea what could be causing this behavior? I've uploaded the two test files in [this gist](https://gist.github.com/OlivierBlanvillain/103a801b0b38589c0032ee23cec9482e), processing these files requires cherry-picking few commits from my [work in progress branch](https://github.com/OlivierBlanvillain/stainless/tree/cats) on top of master.

**Comment by jad-hamza** [comment]
The problem seems to be coming from the function [inlineChecks](https://github.com/epfl-lara/stainless/blob/0a3339a9bb7f763abbc23916b3ed3e73a258f873/core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala#L1064) (thanks Marco for the help).

Do we need the recursive calls to this function?

**Comment by samarion** [comment]
We can probably replace the recursive calls by a preMap, but I'm not sure
that would help performance...

InlineChecks is quite important for the performance of verification later
in the pipeline. Maybe the inlining can be made a bit more efficient, I'd
have to look at the concrete example.

**Comment by mantognini** [comment]
As a quick *temporary* workaround, one can replace [this line](https://github.com/epfl-lara/stainless/blob/0a3339a9bb7f763abbc23916b3ed3e73a258f873/core/src/main/scala/stainless/extraction/oo/TypeEncoding.scala#L1093) by:

```
.withFunctions(newSymbols.functions.values.toSeq.par.map(fd => fd.copy(fullBody = inlineChecks(fd.fullBody))).seq)
//                                              ^^^^                                                         ^^^^
```

and leverage multithreading computation.

**Comment by samarion** [comment]
Sure, sounds good to me. What kind of speedups does this give us?
In the long term, we should have all transformers follow an on-demand and
maximally parallel pattern anyway.

**Comment by OlivierBlanvillain** [comment]
That won't solve the exponential behavior, in it's current state [my experiment on cats](https://github.com/OlivierBlanvillain/cats/tree/proofs) takes 16 minutes to pass the extraction.

**Comment by jad-hamza** [comment]
@OlivierBlanvillain Does your experiment still work if you completely remove the call to inlineChecks on this same line? And how does this affect the 16 minutes?

**Comment by OlivierBlanvillain** [comment]
Down to 35 seconds after https://github.com/OlivierBlanvillain/stainless/commit/8af1f7d2d7d177f2b96b878f4019ecefc43c7fe4 :tada:

**Comment by samarion** [comment]
We should try to replace the inlineChecks function by a specialized version
of the SimplifierWithPC (this is the use case I actually wrote it for
initially).

**Comment by jad-hamza** [comment]
The problem seems to be that `isInstanceOf` is replaced by multiple versions of `isInstanceOf` which leads to a blowup of the tree. The goal of this function is to simplify/optimize the formulas given to the solver right?

I ran `sbt it:test` with and without the call to inlineChecks, here are the results (3498s vs 3553s).

[inlinechecks.txt](https://github.com/epfl-lara/stainless/files/1080402/inlinechecks.txt)
[noinlinechecks.txt](https://github.com/epfl-lara/stainless/files/1080403/noinlinechecks.txt)

**Comment by samarion** [comment]
The whole type encoding system is experimental and targeted at supporting
Scala types in Stainless. Since this support isn't really complete, we
don't have any tests that use this for now. We probably need a few more
significant optimizations before Scala types are really useful... this
means that all our benchmarks (except for Olivier's stuff) don't exercise
this code (much).

About the tree blowup: this inlining serves to replace calls to isSubtypeOf
where one of the arguments is a concrete type. In such cases, inlining the
function and simplifying should produce trees that are more or less
polynomial in the size of the concrete input type. However, this
simplification is currently only applied when going to the solver so we
have an exponential blowup during transformations.

Since type encoding is highly experimental, this issue (along with
https://github.com/epfl-lara/stainless/issues/39,
https://github.com/epfl-lara/stainless/issues/36 and
https://github.com/epfl-lara/stainless/issues/34) can all be grouped
together under "making Scala types work correctly". I won't be able to work
on this in the near future but am open to providing insight in what needs
to be done / how to do it if someone is interested in working on this.

So it may not be useful to focus in this particular issue as it shouldn't
impact current Stainless verification much and fixing it won't make much
sense unless we fix the larger issues with Scala type support.

**Comment by samarion** [comment]
The new type encoding approach has resolved this issue.
