### ISSUE TITLE
@induct breaks proofs?

### ISSUE THREAD

**Issue by BLepers** [epfl-lara/stainless#53]
```scala
import stainless.collection._
import stainless.annotation._

object DataRacing {
   case class SharedState(val rqs:BigInt => List[BigInt]);

   @induct
   def isTree(s:SharedState, content:List[BigInt], id:BigInt):Boolean = {
      require(content.forall(e => e < id && e >= 0))
      content match {
         case Nil() => true
         case Cons(t, ts) =>
            isTree(s, ts, id) && isTree(s, s.rqs(t), t)
      }
   }
}
```

This function verifies, but shouldn't (nothing says that s.rqs(...) matches the requirements).
When the @induct is removed stainless finds a counter example.

Is that an expected behaviour?

**Comment by BLepers** [comment]
Also, related to what the function is trying to do: what is the best way in Stainless to check that a data structure is a tree (i.e., contains no loop)? (I want to prove that a recursion on a hierarchical structure ends, but so far I didn't really find a convenient way to express that. :/)

**Comment by jad-hamza** [comment]
How is the data structure represented?

With @induct the VC to check is the following:
```scala
((¬content.isInstanceOf[Nil[BigInt]] && content.isInstanceOf[Cons[BigInt]])) ==> {
  val t: BigInt = content.asInstanceOf[Cons[BigInt]].h
  val ts: List[BigInt] = content.asInstanceOf[Cons[BigInt]].t
  (
    isTree(s, ts, id) && 
    content.isInstanceOf[Cons[BigInt]] && 
    forall[BigInt](content, (e: BigInt) => (e < id && e >= 0)) && 
    (forall[BigInt](ts, (e: BigInt) => (e < id && e >= 0)) ==> forall[BigInt](s.rqs(t), (e: BigInt) => (e < t && e >= 0)))
  ) ==> 
    forall[BigInt](s.rqs(t), (e: BigInt) => (e < t && e >= 0))
}
```

Does the condition ` (forall[BigInt](ts, (e: BigInt) => (e < id && e >= 0)) ==> forall[BigInt](s.rqs(t), (e: BigInt) => (e < t && e >= 0)))` come from the `induct` tactic?

Perhaps this is related to non-termination. Does this program terminate? (Stainless says yes)

**Comment by BLepers** [comment]
Currently the data structure is as follows: every node has a list of successors, and leafs are node with no successor (rqs(leafId) = Nil()).

Currently the issue to prove anything with that structure is the possible presence of loops. I'm trying to have a structure that doesn't have loops (either by construction, or via requirements).

This program should terminate if the rqs follow the pre-condition of the require() : the ids strictly decrease at each recursive call (so no loops are possible). I'm a bit surprised that stainless can figure that out automatically though :)

**Comment by jad-hamza** [comment]
For the data structure, we could define a function `longestChain(node: BigInt, successors: BigInt => List[BigInt], maxID: BigInt): Option[BigInt]`, that returns the size of the longest chain if it exists, or None is the structure is cyclic or if you encounter a node with negative ID or above `maxID`. This function can be implemented by a graph search, by keeping the set of visited nodes along the way and by stopping as soon as you see an already visited node. We should be able to prove that this function terminates, because the size of the set of visited nodes is bounded by `maxID`.

We can then prove that if `longestChain(node, successors, maxID) = Some(a)`, then `longestChain(node', successors, maxID) = Some(b)` with b < a, where node' is any successor of node. We may then be able to prove the `longestChain` measure decreases when doing recursive calls to successors, in any structure where `longestChain(node, successors, maxID) = Some(a)`.


> I'm a bit surprised that stainless can figure that out automatically though

I think it figures that out by unrolling `content.forall(e => e < id && e >= 0)` once (because `t` is the head of `content`). I'm still not sure why the precondition check for `isTree(s, s.rqs(t), t)` passes.

**Comment by samarion** [comment]
So this was due to a pretty subtle bug in the way we were trying to establish precondition checks through induction. I've now fixed the issue.

About the termination question, that was due to another bug in the termination checker :) which I've now also fixed. Stainless does not infer the ranking function that you need here as we don't try argument permutations when considering termination through lexicographic ordering.

Thanks for reporting!
