### ISSUE TITLE
Recursive references through non-structural types

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#551]
On this file I get an encoding error when solving the verification condition associated with the assertion.

```scala
import stainless.lang.Map
import stainless.lang.StaticChecks.assert

object Test {
  def f(m: Map[BigInt, BigInt]): Unit = {
    require(m == Map())
    assert(true)
  }
}
```

There are various workarounds:
* Write explicitly the type in `require(m == Map[BigInt, BigInt]())` (which is otherwise understood as `Nothing`)
* Use the normal `assert` or `proof.check` instead of `StaticChecks.assert` (??)

Here's the output:

```
[ Debug  ] Generating VCs for those functions: f$30
[ Debug  ] Checking Verification Conditions...
[  Info  ]  - Now solving 'body assertion' VC for f @7:5...
[ Debug  ] Map(choose(((res: Map[Object, Object]) @unchecked) => ∀x: BigInt. (Option(asOption[BigInt, Object](m(x), (x: BigInt) => Integer(x), (x: Object) => x.value)) == res(Integer(x))))) ≠ Map({* -> Option(asOption[{ x: Object | @unchecked false }, Object](None[{ x: Object | @unchecked false }](), (x: { x: Object | @unchecked false }) => x, (x: Object) => x))}) || @ghost true
[ Debug  ] Solving with: nativez3
[ Error  ] Map[Object, Object]@?:? (of class inox.ast.Types$MapType) is unsupported by solver z3:
[ Error  ]   Encountered ADT that can't be defined.
[ Error  ] It has recursive references through non-structural types (such as arrays, maps, or sets): Map[Object, Object]
[  Info  ]  - Result for 'body assertion' VC for f @7:5:
[Warning ]  => UNKNOWN
[ Debug  ] Generating VCs for those functions: 
[ Debug  ] Checking Verification Conditions...
[  Info  ]   ┌───────────────────┐
[  Info  ] ╔═╡ stainless summary ╞══════════════════════════════════════════════════════════════════════╗
[  Info  ] ║ └───────────────────┘                                                                      ║
[  Info  ] ║ f  body assertion    unknown   nativez3   File.scala:7:5      0,042 ║
[  Info  ] ╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
[  Info  ] ║ total: 1    valid: 0    (0 from cache) invalid: 0    unknown: 1    time:   0,042           ║
[  Info  ] ╚════════════════════════════════════════════════════════════════════════════════════════════╝
[  Info  ] Shutting down executor service.
```

**Comment by romac** [comment]
> Write explicitly the type in require(m == Map[BigInt, BigInt]()) (which is otherwise understood as Nothing)

I think specifying the type fixes the issue because otherwise there is indeed a recursive reference to `Map` itself via one of the constructors of `Object`.

 > Use the normal assert or proof.check instead of StaticChecks.assert (??)

Now this is very puzzling…

**Comment by romac** [comment]
> > Use the normal assert or proof.check instead of StaticChecks.assert (??)

> Now this is very puzzling…

I figured out why the behaviour was different between `scala.Predef.assert` and `stainless.lang.StaticChecks.assert`.

In the former case the assertion was just `assert(true)`, which prompted the VC generator to just emit a VC for `true`, without the surrounding context.

In the latter case, it was `assert(@ghost true)` which does not trigger the same behaviour and yield the full VC containing the malformed Map, etc. which was then rightly rejected by Inox.

We now remove the annotation in `ImperativeCleanup`, which means that both assertions yield the same VC, ie. `true` which then goes through. Note that changing the assertion to eg. `assert(m.isEmpty)`

Now the question is: should we…

- always keep the full context around so that Inox can reject VCs which appear in an invalid "context"?
- perform such validity check ourselves before generating the VCs?
- keep things as is

@jad-hamza @samarion What do you think?

**Comment by romac** [comment]
Actually, never mind, let's not remove the `@ghost` annotation after `imperative` as it might be useful down the pipeline. I suggest we simply ignore such annotations when generating VCs instead.

The question above still stands.

**Comment by romac** [comment]
For reference, with `--type-checker`, both cases are rejected with

> Run has failed with error: stainless.verification.TypeCheckerUtils$TypeCheckingException: ADT Object$0 must appear only in strictly positive positions of Object$0
