### ISSUE TITLE
Verification hangs on simple recursive function

### ISSUE THREAD

**Issue by nathaniel-may** [epfl-lara/stainless#597]
Verification hangs on simple fibonacci implementation.

Command: `stainless ~/git/Sandbox/src/main/scala/example/Example.scala`
Code:
```scala
import stainless.lang._

object Example {
  def fib(n: Int): Int =
    if (n <= 0)      0
    else if (n == 1) 1
    else             fib(n-1) + fib(n-2)

  def fib_lemma(x: Int): Boolean = {
    if(x < 0) fib(x)   == 0
    else      fib(x+2) == fib(x) + fib(x+1)
  } holds
}
```

Output after termination:
```
^C[  Info  ] 
[Warning ] Interrupted...
[  Info  ]  - Result for 'postcondition' VC for fib_lemma @15:3:
[Warning ]  => CANCELLED
[  Info  ]  - Checking cache: 'postcondition' VC for fib_lemma @15:3...
[  Info  ] Cache miss: 'postcondition' VC for fib_lemma @15:3...
[  Info  ]  - Now solving 'postcondition' VC for fib_lemma @15:3...
[  Info  ]  - Result for 'postcondition' VC for fib_lemma @15:3:
[  Info  ]  => VALID
[  Info  ]   ┌───────────────────┐
[  Info  ] ╔═╡ stainless summary ╞════════════════════════════════════════════════════════════════════════════════════════╗
[  Info  ] ║ └───────────────────┘                                                                                        ║
[  Info  ] ║ fib_lemma  postcondition  cancelled  nativez3  ../Sandbox/src/main/scala/example/Example.scala:15:3  903.809 ║
[  Info  ] ║ fib_lemma  postcondition  valid      nativez3  ../Sandbox/src/main/scala/example/Example.scala:15:3  0.064   ║
[  Info  ] ╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
[  Info  ] ║ total: 2    valid: 1    (0 from cache) invalid: 0    unknown: 1    time: 903.873                             ║
[  Info  ] ╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
[  Info  ] Shutting down executor service.
```

But it should fail. Counter example to the lemma: `x = Int.MaxValue-1`

**Comment by jad-hamza** [comment]
Unfortunately I don't think Stainless will be able to find this counter-example, because it requires unfolding the definition of `fib` roughly `Int.MaxValue` times. Every time a recursive function is unfolded, a new query is made to the SMT solvers with the unfolded program. Also, I'm not sure how unfolding works but unfolding `fib` `n` times will probably create a program with size exponential in `n`.

Stainless works best when it only needs to unfold recursive functions once or twice to establish properties or find counter-examples.

I tried:

```scala
  def test(n: Int) = {
    fib(n) != 89
  } holds
```

Stainless finds the counter-example `n = 11` in a bit less than a minute, but with:

```scala
  def test(n: Int) = {
    fib(n) != 144
  } holds
```

Stainless times out after 60 seconds.

For your original program, Stainless can also catch potential overflows with the option `--strict-arithmetic`.

**Comment by nathaniel-may** [comment]
Ok that makes sense. I tried it with `--strict-arithmetic` and even though I terminated a couple of the processes early it did find the counter example which is pretty cool. And ultimately when I change all the `Int`s to `BigInt` it verifies quickly so that's great.

Thanks for the help!
