### ISSUE TITLE
Exception in SMTLIBParser

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#6]
This file produces an exception when run with stainless-scalac (corresponding tip-session attached)

```scala
import stainless.collection._
import stainless.lang._
import stainless.annotation._

object Crash {
  
  @induct
  def falseTheorem(k: BigInt, domain: List[BigInt]) = {
    require(domain.contains(k))
       
    false
  
  } holds
}
```

[crash.txt](https://github.com/epfl-lara/stainless/files/738913/crash.txt)

**Comment by samarion** [comment]
Well, this is due to the Z3 binary interface using identifiers of the shape `k!0`, `k!1`, etc. to encode models for arrays (and sets, in this case). Your `k` input variable also gets translated to `k!0` in the Z3 smtlib interface and we therefore have a collision...

I fixed the issue in the latest version of Inox but I won't bump the version for such a minor issue so this probably won't be available in stainless for a while. You can circumvent the issue either by using a different solver than smt-z3 or by avoiding the name `k` for your variables.
