### ISSUE TITLE
Upgrade Dotty to new version

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#713]
cc: @vkuncak 

Specifically the brace-free indent-sensitive syntax

**Comment by romac** [comment]
To my knowledge that is currently impossible, at least until we manage to compile Inox, Stainless and their dependencies with Dotty itself, as Dotty does not bootstrap from Scala 2.12 anymore [since version 0.17.0-RC1](https://dotty.epfl.ch/blog/2019/07/25/17th-dotty-milestone-release.html).

I can see if I can get Inox to compile with Dotty, but that's still a tall order imho. Because of that, I am afraid that until TASTy is ready, we are stuck with earlier versions of Dotty (currently on 0.12, I did not manage to upgrade to later versions (but pre 0.17) back then, but can't remember exactly why unfortunately.

Ping @gsps in case I am misinformed or missing something.

**Comment by vkuncak** [comment]
Let's just wait until there is a tool that automatically migrates our code to whatever version of Dotty will be current when such tool is available.

**Comment by romac** [comment]
Scala 3 support should be done via a TASTy front-end instead.
