### ISSUE TITLE
Prevent impure lazy vals in function bodies

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#808]

**Comment by vkuncak** [comment]
Here is a test case:
```scala
  def f(): Int = {
    var counter = 0
    lazy val x = {
      counter = counter + 1
      counter
    }
    counter + x + x
  } ensuring (_ == 2)
```
For now (1) we can reject and report cleanly, since Scala style probably does not rely on local lazy val-s much.
Later (2) as @jad-hamza suggested, we could factor out into a method. We already pull out methods for while loops, so doing it for lazy vals seems fine. It means that if you use a lazy val and the computation is pure, there will be some verification penalty.
Eventually (3) we could optimize some of the lazy vals into vals as long as we are sure there are no side effects and termination still works.

**Comment by jad-hamza** [comment]
(1) implemented by https://github.com/epfl-lara/stainless/pull/814
