### ISSUE TITLE
Abstract values must be overridden with fields

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#813]
Running:
```
stainless-scalac frontends/benchmarks/typechecker/valid/MicroTests/FieldInheritance.scala
```
fails with the error:
```
[ Error  ] frontends/benchmarks/typechecker/valid/MicroTests/FieldInheritance.scala:13:3: Abstract values `y` must be overriden with fields in concrete subclass
             case class Bar[X](override val thisIsIt: BigInt, weird: X) extends Foo[X] {
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
[ Error  ] frontends/benchmarks/typechecker/valid/MicroTests/FieldInheritance.scala:17:3: Abstract values `y` must be overriden with fields in concrete subclass
             case class Baz[X](weird: X) extends Foo[X] {
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
[ Fatal  ] Aborting from SplitCallBack
```

**Comment by jad-hamza** [comment]
The `y` of `Bar` (and `Baz`) doesn't appear in `desc.fields`, so an exception is thrown in `TreeSanitizer.scala`. Should we use `desc.methods` here?

https://github.com/epfl-lara/stainless/blob/2372c03de6e9cba91d267a9e63f1504718ea264e/core/src/main/scala/stainless/extraction/xlang/TreeSanitizer.scala#L406-L426

**Comment by jad-hamza** [comment]
Is this fix ok? https://github.com/epfl-lara/stainless/pull/810/commits/13f7117035b284fbbf962bae83f70190799e083f

**Comment by samarion** [comment]
Hmm, I don't remember exactly.

I thought we had concluded that overriding abstract vals outside of constructor params was illegal (so your example should be rejected). I think we would have an issue if there was a variable `val x = y` after the declaration of `y` in `Foo` since it would be null during construction of `Foo`, or something like that.

@romac: do you recall the exact issue?

**Comment by romac** [comment]
This restriction was apparently introduced in https://github.com/epfl-lara/stainless/pull/712 but it's not clear to me anymore what it actually had to do with that specific feature (ie. lifting invariants of value classes as refinements).

Perhaps it's something we thought of along the way and I (wrongly) bundled it in this PR with little to not context, sorry about that.

Oh, now that I think about it, this prevents overriding an abstract `val` with a `def` which may assume the invariant. Since `val`s can be referred to in an invariant, that may lead to a "cyclic dependency" and thus some unsoundness. Sorry if this is all a bit fuzzy.

**Comment by jad-hamza** [comment]
> Oh, now that I think about it, this prevents overriding an abstract `val` with a `def` which may assume the invariant. Since `val`s can be referred to in an invariant, that may lead to a "cyclic dependency" and thus some unsoundness. Sorry if this is all a bit fuzzy.

If I filter with `isGetter` that will prevent this right?

https://github.com/epfl-lara/stainless/commit/13f7117035b284fbbf962bae83f70190799e083f#diff-840d5c0f3f08a061b7f7f89fd4f3b331R409

**Comment by samarion** [comment]
I'm not clear exactly which behavior you're trying to allow here.

Could you please add the following invalid benchmarks somewhere:
```scala
import stainless.lang._

object FieldInheritance2 {

  sealed abstract class Foo[B] {
    val thisIsIt: BigInt = 1
    val y: BigInt
    val z: BigInt = y
  }

  case class Bar[X](override val thisIsIt: BigInt) extends Foo[X] {
    val y = thisIsIt
  }

  def foo[A](f: Foo[A]) = {  f.y == f.z }.holds // wrong because f.z is always null
}
```
Whichever solution you come up with, this program should be rejected.

I think the general principle should be that vals can only be overridden by constructor parameters (= fields) because those will be set before anything else. If you want to override something in the class body, it should be a def.

**Comment by jad-hamza** [comment]
I see thanks. The error message that is reported for the original post above is good then? I'll just revert the https://github.com/epfl-lara/stainless/commit/13f7117035b284fbbf962bae83f70190799e083f change in #810, and remove `FieldInheritance.scala` from the valid tests.

**Comment by samarion** [comment]
Yes, I think that should work. Maybe also add a comment in `TreeSanitizer.scala` that explains the logic a bit so we don't forget again :)

One other issue I've realized is that abstract defs shouldn't be overriden by (non-field) vals because you run into the same nullness problem. We should also add a check for that in the `TreeSanitizer`.

**Comment by jad-hamza** [comment]
Thanks! Closed as this is not a bug.
