### ISSUE TITLE
Stainless yields lambdas with unsatisfiable preconditions (ie. an invalid model)

### ISSUE THREAD

**Issue by romac** [epfl-lara/stainless#92]
@jad-hamza and I ran into the following issue today:

The following testcase yields a counter-example with an unsatisfiable precondition, which is catched by `--check-models` as an invalid model.

```scala
import stainless.lang._

object util {
  @inline
  def total[A, B](f: A => B): Boolean = forall { (a: A) =>
    f.pre(a)
  }
}

case class Cont[R, A](run: (A => R) => R) {

  import util._

  require(total(run))

  def map[B](f: A => B): Cont[R, B] = {
    require(total(f))

    Cont { (k: B => R) =>
      // require(true) // TODO: Report issue
      this.run(x => k(f(x)))
    }
  }
}
```

```
(snip...)

[  Info  ]  - Now solving 'lambda precondition' VC for map @24:21...
[ Debug  ] @unchecked ∀a: A. f.pre(a) ==> k.pre(f(x))
[ Debug  ] Solving with: nativez3
[  Info  ]  - Result for 'lambda precondition' VC for map @24:21:
[Warning ]  => INVALID
[Warning ] Found counter-example:
[Warning ]   x: A        -> A#0
[Warning ]   k: (B) => R -> (x$524: B) => {
[Warning ]     require(if (x$524 == B#0) {
[Warning ]       false
[Warning ]     } else {
[Warning ]       false
[Warning ]     })
[Warning ]     R#0
[Warning ]   }
[Warning ]   f: (A) => B -> (x$541: A) => if (x$541 == A#0) {
[Warning ]     B#0
[Warning ]   } else {
[Warning ]     B#0
[Warning ]   }

(snip...)
```
On the other hand, explicitly specifying `require(true)` as a precondition inside of the lambda makes the testcase validates.

```scala
import stainless.lang._

object util {
  @inline
  def total[A, B](f: A => B): Boolean = forall { (a: A) =>
    f.pre(a)
  }
}

case class Cont[R, A](run: (A => R) => R) {

  import util._

  require(total(run))

  def map[B](f: A => B): Cont[R, B] = {
    require(total(f))

    Cont { (k: B => R) =>
      require(true)
      this.run(x => k(f(x)))
    }
  }
}
```

```
(snip...)

[  Info  ]  - Now solving 'lambda precondition' VC for map @24:23...
[ Debug  ] @unchecked ∀a: A. f.pre(a) ==> f.pre.pre(x)
[ Debug  ] Solving with: nativez3
[  Info  ]  - Result for 'lambda precondition' VC for map @24:23:
[  Info  ]  => VALID

(snip...)
```

Is is not clear to me:

a) why such a precondition should be considered
b) why explicitly adding `require(true)` makes the issue go away. Shouldn't it be the default for a lambda with no explicit precondition?

CC: @vkuncak @samarion

**Comment by romac** [comment]
Also, it seems to me that synthesizing any kind of precondition for lambdas taken as arguments to another function/lambda kind of defeats the purpose of equational reasoning. How can one expect to even carry such a proof by hand under those assumptions?

**Comment by jad-hamza** [comment]
I think it has to do with the injection of preconditions. In the first example, the following preconditions are injected automatically. On my machine, with a recent github version of Z3, I obtain a valid counter-example. Though it's hard to understand what the counter-example refers to, because there are 9 (!) lambda precondition checks for line 21.

On the second example, since we have already written a precondition ourselves (`require(true)`), Stainless assumes that we know what we're doing and will not inject a precondition. Maybe this is a reasonable choice, but we should perhaps add some kind of warnings.

```scala
def map[R, A, B](thiss: Cont[R, A], f: (A) => B): Cont[R, B] = {
  require({
    val f: (A) => B = f
    @unchecked ∀a: A. f.pre(a)
  })
  Cont[R, B]((k: (B) => R) => {
    require(thiss.run.pre(((x: A) => k(f(x)))))
    thiss.run(((x: A) => {
      require(f.pre(x) && k.pre(f(x)))
      k(f(x))
    }))
  })
}
```


What if we introduced a symbol -=> that represents total functions, similarly to F* ?
Then we use the type A -=> B everywhere instead of A => B.
The following program verifies; I hope this helps!

```scala
import stainless.lang._

object util {
  @inline
  def total[A, B](f: A => B): Boolean = forall { (a: A) => f.pre(a) }
  
  case class -=>[A,B](f: A => B) {
    require(total(f))
    def apply(a: A) = f(a)
  }

  implicit def funToTotalFun[A,B](f: A => B): A -=> B = {
    require(total(f))
    -=>(f)
  }

  case class Cont[R, A](run: (A -=> R) -=> R) {
    def map[B](f: A -=> B): Cont[R, B] = {
      Cont { (k: B -=> R) =>
        this.run((x: A) => k(f(x)))
      }
    }
  }

}
```

**Comment by jad-hamza** [comment]
In @romac examples, is it normal to have verification conditions that refer to `f.pre.pre`? I guess that makes sense because we're calling `f.pre(x)` (in the `total` function), so we want to make sure that `f.pre(x)` is well defined, and that `f.pre.pre(x)` holds. But since in the VC we are calling `f.pre.pre`, shouldn't we also make sure that `f.pre.pre(x)` is well defined as well, and that `f.pre.pre.pre(x)` holds? (and so on).

**Comment by samarion** [comment]
`f.pre.pre(x)` is always true by convention (and it's checked by the higher-order contract checker). We should probably simplify such expressions out from the formula to avoid confusion.

As @jad-hamza said, there is indeed an invalid lambda precondition in this program (namely `require(k.pre(f(x)))` since Stainless has no way of knowing that `forall y. k.pre(y)`. However, I would have expected this precondition to be inferred, I'll have to check what's going on.

What's more worrisome is that the version with the extra `require(true)` is fine. The same check should fail in that case I believe. I'll try to take a look this weekend.

About the total functions, I completely agree that these would be great. I actually implemented dedicated support within Inox for simplifications assuming purity but these assume the whole program contains only total functions. I wonder if this would be possible on a per-function level. In the mean time, @jad-hamza 's encoding into an ADT should work fine (though it might be difficult to have it look as nice with multi-parameter functions).

**Comment by jad-hamza** [comment]
```scala
(x: A) => {
      require(f.pre(x) && k.pre(f(x)))
      k(f(x))
    }
```
This expression E1 should be fine, because the precondition ensures that k(f(x)) is defined.

Then, since `run` is total, the expression E2
```scala
thiss.run(((x: A) => {
      require(f.pre(x) && k.pre(f(x)))
      k(f(x))
    }))
```
should be OK for Stainless as well.

The expression E3
```scala
(k: (B) => R) => {
    require(thiss.run.pre(((x: A) => k(f(x)))))
    thiss.run(((x: A) => {
      require(f.pre(x) && k.pre(f(x)))
      k(f(x))
    }))
  }
```
is the creation of lambda.

Then I guess there are two cases. Either E3 has the precondition `require(thiss.run.pre(((x: A) => k(f(x)))))`, and in that case Stainless is right not to verify the program, because `Cont` is expecting only total functions. Or E3 has no precondition (`require(true)`), and in that case we can freely give E3 to `Cont`. So Stainless is maybe giving the correct answer for both examples?

I'm thinking perhaps we shouldn't inject preconditions ourselves, as for complex programs such as these ones, it's hard to understand what's going on without reading the transformed program that is given to Inox (and that the user never sees). Then if we want total functions, we can either write the conditions ourselves, or use another symbol (e.g. -=> as above), or maybe flip a Stainless option that makes all higher-order functions total by default.

**Comment by samarion** [comment]
Ah yes, you're right. I was under the impression that E1 wouldn't be ok because we can't check the precondition at creation time (but that's not what should happen).

There's still something not quite right with the preconditions. It seems to me that E3 with inferred preconditions should be
```scala
(k: (B) => R) => {
    require(thiss.run.pre(((x: A) => {
      require(f.pre(x) && k.pre(f(x)))
      k(f(x))
    })))
    thiss.run(((x: A) => {
      require(f.pre(x) && k.pre(f(x)))
      k(f(x))
    }))
  }
```

However, given the path condition, E3 should be total here (since we know that `this.run.pre(...)` holds). So Stainless should verify both versions, no? Maybe it will with the adapted preconditions.

Higher-order contracts with input functions are quite unintuitive. In this case, given that `k` is not required to be total, Stainless should in fact complain when `Cont` is instantiated with a function that tries to apply `k`, right? Is that actually the case?

I agree that the higher-order contracts are quite hard to reason about since we don't really see them. Maybe we should have functions be total by default and let users specify they want partial functions when necessary. I'll need to think about whether it's possible to have both cases co-exist nicely.

**Comment by jad-hamza** [comment]
> So Stainless should verify both versions, no? Maybe it will with the adapted preconditions.

Yes I have tried and this is right, it verifies with the precondition you wrote.

> Stainless should in fact complain when Cont is instantiated with a function that tries to apply k, right? Is that actually the case?

Yes you're right, the VC that doesn't hold is this one: `∀a: A. f.pre(a) ==> k.pre(f(x))`

**Comment by romac** [comment]
> On 27 Oct 2017, at 15:12, Nicolas Voirol <notifications@github.com> wrote:
> 
> I agree that the higher-order contracts are quite hard to reason about since we don't really see them. Maybe we should have functions be total by default and let users specify they want partial functions when necessary. I'll need to think about whether it's possible to have both cases co-exist nicely.
> 
+1

Considering functions potentially partial by default really defeats the purpose of equations reasoning, and makes it hard to reason about laws, etc.

**Comment by jad-hamza** [comment]
Yes the default => function type should probably represent total functions, and then we could have another class or wrapper for partial functions. @vkuncak was suggesting:
```scala
case class PartialFun[A,B](pre: A => Boolean, f: A => B) {
  def apply(a: A) = {
    require(pre(A))
    f(a)
  }
}
```
or
```scala
case class PartialFun[A,B](f: A => Option[B]) {
  def apply(a: A): B = {
    require(f(a) != None)
    f(a).get
  }
}
```
 
Then, we would not allow `require` on closures, unless the closure is wrapped in a `PartialFun`. So by default all closures would be checked to be total.

**Comment by mantognini** [comment]
This first design also has the advantage to be closer to Scala's library `PartialFunction` vs `Function1`. It's arguably not a main goal to have an interface close the Scala's library, yet it has some positive aspects, such as making the code more Scala-natural to write.

**Comment by romac** [comment]
@samarion We just tried to hack something together very quickly with @jad-hamza in order to get rid of pre-conditions for lambda applications (assuming they are total), is that a good first step:

```scala
diff --git a/core/src/main/scala/stainless/extraction/package.scala b/core/src/main/scala/stainless/extraction/package.scala
index bac63e0..8dfcde2 100644
--- a/core/src/main/scala/stainless/extraction/package.scala
+++ b/core/src/main/scala/stainless/extraction/package.scala
@@ -76,6 +76,6 @@ package object extraction {
     val extracted: Program { val trees: extraction.trees.type } =
       program.transform(pipeline)
 
-    new PreconditionInference(extracted, ctx).targetProgram
+    extracted
   }
 }
diff --git a/core/src/main/scala/stainless/verification/DefaultTactic.scala b/core/src/main/scala/stainless/verification/DefaultTactic.scala
index 43bad33..34e4efb 100644
--- a/core/src/main/scala/stainless/verification/DefaultTactic.scala
+++ b/core/src/main/scala/stainless/verification/DefaultTactic.scala
@@ -88,8 +88,8 @@ trait DefaultTactic extends Tactic {
       case (a @ Assert(cond, _, _), path) =>
         (a, path implies cond)
 
-      case (app @ Application(caller, args), path) =>
-        (app, path implies Application(Pre(caller), args))
+      // case (app @ Application(caller, args), path) =>
+      //   (app, path implies Application(Pre(caller), args))
 
       case (c @ Choose(res, pred), path) if !(res.flags contains Unchecked) =>
         (c, path implies Not(Forall(Seq(res), Not(pred))))
```

I know it's a hack and there's a lot more to think about carefully, but as a hack, we were wondering what would be the best way to not generate any precondition (especially not `require(false)`) for lambdas that are synthesized as part of a model?

**Comment by romac** [comment]
@mantognini I agree that having partial functions be a (implicit?) subtype of total function is closer to Scala, but at the same time, having `PartialFunction` extends `Function1` is an heresy that afaict violates the the [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle). What do you think? Keeping in mind that partial function are antithetic to functional programming overall :p

**Comment by romac** [comment]
I guess at some point we need to decide whether we want to see Stainless as a theorem prover or as a Scala verification tool. Which is a debate on its own that is probably outside of the scope of this issue but maybe worth having at some point. @jad-hamza @samarion

**Comment by samarion** [comment]
@romac In order to not have preconditions in your models, you also need to modify `InoxEncoder` to not encode functions into the (pre,body) tuples. Not sure exactly what else needs to be done without actually writing the code :)

About partial functions, I'm not sure I would say they are antithetic to functional programming. They may be in discord with functional language theory and certainly with HOL but, in practice, any real-world functional programming language will readily accept partial functions. However, I do agree that having `PartialFunction <: Function` is not acceptable in Stainless as checks will have to be performed when trying to convert a `PartialFunction` to a `Function`.

For the theorem prover vs Scala verifier question, I'm firmly in the verifier camp. The input language, interaction model, and grounding in operational semantics don't make much sense for a TP in my mind (though we do need to clarify the edge case of quantifiers at some point...) That is not to say that Stainless can't or shouldn't be used for theorem proving, but these "theorems" will be defined with respect to operational semantics, which is maybe not quite typical.
However a related question is: do we want to have dedicated support (and how much so) for more logical constructs like lemmas or total first-class functions.

**Comment by jad-hamza** [comment]
> a theorem prover or as a Scala verification tool

We don't to prove theorems about Scala programs :)

> you also need to modify InoxEncoder to not encode functions into the (pre,body) tuples

Thanks that's what we were missing!

**Comment by romac** [comment]
> @romac In order to not have preconditions in your models, you also need to modify InoxEncoder to not encode functions into the (pre,body) tuples. Not sure exactly what else needs to be done without actually writing the code :)

Thansk! I took a stab at this in #111.

> About partial functions, I'm not sure I would say they are antithetic to functional programming. They may be in discord with functional language theory and certainly with HOL but, in practice, any real-world functional programming language will readily accept partial functions. However, I do agree that having PartialFunction <: Function is not acceptable in Stainless as checks will have to be performed when trying to convert a PartialFunction to a Function.

Yes that was maybe too strong a word, sorry about that. I actually agree with what you're saying.

> For the theorem prover vs Scala verifier question, I'm firmly in the verifier camp. The input language, interaction model, and grounding in operational semantics don't make much sense for a TP in my mind (though we do need to clarify the edge case of quantifiers at some point...) That is not to say that Stainless can't or shouldn't be used for theorem proving, but these "theorems" will be defined with respect to operational semantics, which is maybe not quite typical.

Makes sense 👍

**Comment by samarion** [comment]
We now have total lambdas by default and partial functions with distinct types, so this should be fixed.
