### ISSUE TITLE
Internal error with using ignore annotation

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#98]
It's not a big deal but if `@ignore` is not meant for the user, we should probably change the error message. But then it's perhaps not easy to differentiate between the `@ignore`'s written by the user, and the legitimate ones from the library?

```scala
import stainless.annotation._

object SI_Ignore {
    @ignore
    def f(x: Int) = 0

    def g(x: Int) = f(x)
}
```

**Comment by mantognini** [comment]
It seems `f` is not extracted at all:

```
...
[ Debug  ] Got a unit for /localhome/mantogni/stainless/frontends/scalac/target/scala-2.11/classes/stainless/math/package.scala: math with:
[ Debug  ]      functions -> [abs, max, max, min, min]
[ Debug  ]      classes   -> []
[ Debug  ] Got a unit for /localhome/mantogni/SubProjects/Proofs/Tests/SI_Ignore.scala: SI_Ignore with:
[ Debug  ]      functions -> [g]
[ Debug  ]      classes   -> []
[ Error  ] g$1 depends on missing dependencies: f$26.
[Internal] Missing some nodes in Registry: f$26
[Internal] Please inform the authors of Inox about this message
[ Error  ] Rethrowing exception emitted from within the compiler: Missing some nodes in Registry: f$26
```

This annotation is currently defined as

 > Ignore this definition when extracting Stainless trees. This annotation is useful to define functions that are not in Stainless’s language but will be hard-coded into specialized trees, or to include code written in full Scala which is not verifiable by Stainless.

I don't remember exactly what was done in Leon, but I guess we should be extracting something with some kind of `choose` body instead of the actual function body, right?

**Comment by samarion** [comment]
I believe that not extracting it at all is correct. The ignore annotation is used for functions that will be extracted as something else than a function. For example, the ignored `forall` function calls gets extracted as `Forall` ASTs and the `forall` function shouldn't exist within the program.

In order to emit a warning, we would need to compile a set of all symbols that should indeed be ignored (we don't have this for now). Can we maybe make the annotation private within the stainless library?

**Comment by mantognini** [comment]
Looking at the sphinx doc, it seems not all annotations are documented. I thought `@extern` had been removed but it isn't the case. What's the usage of `@internal`? Maybe this one should be used instead of `@ignore` if the usage is meant to be private.

I don't know if an annotation can be made private or not, but we can check whether a symbols is from the library or not:

```diff
diff --git a/frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala b/frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
index 2ace821..934e245 100644
--- a/frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
+++ b/frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
@@ -171,10 +171,12 @@ trait CodeExtraction extends ASTExtractors {
       case EmptyTree =>
         // ignore
 
-      case t if (
-        (annotationsOf(t.symbol) contains xt.Ignore) ||
-        (t.symbol.isSynthetic && !t.symbol.isImplicit)
-      ) =>
+      case t if (annotationsOf(t.symbol) contains xt.Ignore) =>
+        val source = t.symbol.pos.source.file.file.getAbsolutePath
+        if (!(Main.libraryFiles contains source))
+          outOfSubsetError(t, s"@ignore is for internal usage only; error detected on: " + t.symbol.fullName)
+
+      case t if t.symbol.isSynthetic && !t.symbol.isImplicit =>
         // ignore
 
       case ExtractorHelpers.ExSymbol("stainless", "annotation", "ignore") =>
@@ -300,10 +302,12 @@ trait CodeExtraction extends ASTExtractors {
       case EmptyTree =>
         // ignore
 
-      case t if (
-        (annotationsOf(t.symbol) contains xt.Ignore) ||
-        (t.symbol.isSynthetic && !t.symbol.isImplicit)
-      ) =>
+      case t if (annotationsOf(t.symbol) contains xt.Ignore) =>
+        val source = t.symbol.pos.source.file.file.getAbsolutePath
+        if (!(Main.libraryFiles contains source))
+          outOfSubsetError(t, s"@ignore is for internal usage only; error detected on: " + t.symbol.fullName)
+
+      case t if t.symbol.isSynthetic && !t.symbol.isImplicit =>
```

I guess the same can be done for dotc.

**Comment by mantognini** [comment]
Commit available here: https://github.com/epfl-lara/stainless/commit/b308c4d8107be7d849e77c829f0c12f9ff2f3171, branch `fix_ignore`, if you want to have a closer look.

**Comment by samarion** [comment]
But will this fix work with the jar version of the library? Has someone tried with the package-private annotation class?

**Comment by mantognini** [comment]
> But will this fix work with the jar version of the library?

This is not an issue because the library is first extracted to a temporary directory.

> Has someone tried with the package-private annotation class?

I just did. Changing it to `private[stainless] class ignore extends Annotation` seems to work as well. Of course, the user can still work in the `stainless` package but that would be their mistake... This of course has the advantage of being concise and not requiring both frontends to be updated.

However, & related to that, I'm still not 100% sure I understand the intend of all these annotations. Could you give a proper description for all the annotations currently defined in the library? Thanks.

**Comment by samarion** [comment]
Ok, as long as it works with the jar, checking source files is ok with me. However, wouldn't it be better to check when the symbol is used? It seems we're rejecting some cases in the tests that actually make sense (eg. ignoring `main` is fine no? Or do you think extern would be better?).
Please also add this to the rejection tests :)

About annotations:
- ignore: doesn't extract the symbol or its methods (will not be in registry).
- library: doesn't verify the symbol or its methods.
- induct: applies the induct tactic during verification of this function.
- traceInduct(name: String = ""): not (yet?) supported in Stainless I believe.
  We should sync with Ravi to get some actual use cases.
- extern: only extracts the contracts and replaces the function's body with a choose.
- internal: no idea, not used I assume?
- pure: no idea, something with imperative I guess?
- all orb annotations: not used in Stainless.
  There was some discussion at some point with @jad-hamza to support invisibleBody IIRC.
  We need benchmarks for these to see what can be automated and what requires annotation.

**Comment by mantognini** [comment]
Superseded by #139.
